lang: en
author:
  name: bullgit
  email: haroen@bullg.it
  twitter: '@bullgit'
title: Fast Clock
description: A super fast clock continously deployed
url: https://bullg.it
baseurl: /fast-clock
color: '#FFFFFF'
css: ['/src/style.css']
# scripts: ['src/main.js']
favicon: /media/pixels/favicon.png
sass:
  style: compressed
time: 2016-05-02T06:29:47+0000
